### PR TITLE
fix(user-task): prevent npe for non-tenant configurations

### LINKED ISSUE #67: Error "NullPointerException" when opening a user task workers if multi-tenancy is disabled
If multi-tenancy is disabled using the following configuration:
```
vanillabp:
  workflow-modules:
    module1:
      adapters:
        camunda8:
          useTenants: false 
```

a NPE is thrown when opening user tasks workers:
```
java.lang.NullPointerException: Element at index 0 is null.
at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:359) ~[protobuf-java-3.25.3.jar:na]
...
at io.camunda.zeebe.gateway.protocol.GatewayOuterClass$ActivateJobsRequest$Builder.addAllTenantIds(GatewayOuterClass.java:3029) ~[zeebe-gateway-protocol-impl-8.4.5.jar:8.4.5]
at io.camunda.zeebe.client.impl.command.ActivateJobsCommandImpl.send(ActivateJobsCommandImpl.java:120) ~[zeebe-client-java-8.4.5.jar:8.4.5]
...
at io.camunda.zeebe.client.impl.worker.JobWorkerImpl.poll(JobWorkerImpl.java:193) ~[zeebe-client-java-8.4.5.jar:8.4.5]
...
at io.camunda.zeebe.client.impl.worker.JobWorkerImpl.onScheduledPoll(JobWorkerImpl.java:149) ~[zeebe-client-java-8.4.5.jar:8.4.5]
```

### PR DESCRIPTION
**Pull request by coesterheld**
Closes #67

### CODE REVIEW

File: spring-boot/src/main/java/io/vanillabp/camunda8/wiring/Camunda8TaskWiring.java [hunk 1]
```diff
@@ -113,11 +113,10 @@ public void openWorkers() {
                             .jobType("io.camunda.zeebe:userTask")
                             .handler(userTaskHandler)
                             .timeout(Integer.MAX_VALUE) // user-tasks are not fetched more than once
-                            .name(workerId)
-                            .tenantId(tenantId);
+                            .name(workerId);
                     final var workerProperties = camunda8Properties.getUserTaskWorkerProperties(workflowModuleId);
                     workerProperties.applyToUserTaskWorker(userTaskWorker);
-                    return userTaskWorker;
+                    return tenantId != null ? userTaskWorker.tenantId(tenantId) : userTaskWorker;
```
Comment (stephanpelikan) [inline spring-boot/src/main/java/io/vanillabp/camunda8/wiring/Camunda8TaskWiring.java:119]: Please change this line into a separate if-statement: Using a tenaer operate is OK in general but not here in combination with the return statement. It tells that different responses are expected depending on the given condition. But actually, the worker needs to be configured properly depending on the given condition regardless whether it is return by the method or not. Additionally, I would place it underneath line 116 since the tenant is an crucial configuration as the other aspects above line 116 but the configuration in 117/118 are nice-to-haves:

```java
        ...
        .name(workerId);

    if (tenantId != null) {
        userTaskWorker.tenantId(tenantId);
    }

    final var workerProperties = ....
```

**Review by stephanpelikan — CHANGES_REQUESTED** [review]

**Review by stephanpelikan — APPROVED** [review]
